version: '3'
services:
  server:
    build: ./docker
    depends_on:
      - db
    command: npm run start:prod
    environment:
      - MONGODB_URL=mongodb+srv://Vietsalt:Emgaimua1@cluster0.nhyzzlj.mongodb.net/?retryWrites=true&w=majority


    ports:
      - 8080:8080
  db:
    image: mongo:4.2